version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.12"
  jobs:
    pre_create_environment:
        - asdf plugin add uv
        - asdf install uv latest
        - asdf global uv latest
    create_environment:
        - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    install:
        - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --frozen --group docs

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py