Figure height: 3.2
Aspect ratio: 1.3333333333333333
Resolution: 300
Primary linestyle: --
Secondary linestyle: ':'
Model colour: k
Model error colour: C1
Marker border: 0.5
Capsize: 1.5
Errorbar linewidth: 0.7
Markers:
- - blue circle
  - '#648FFF'
  - o
  - 4.27
- - dark lavender square
  - '#785EF0'
  - s
  - 4.05
- - deep pink up-pointing triangle
  - '#DC267F'
  - ^
  - 4.5
- - dark orange down-pointing triangle
  - '#FE6100'
  - v
  - 4.5
- - orange left-pointing triangle
  - '#FFB000'
  - <
  - 4.5
- - yellow right-pointing triangle
  - '#FDDF49'
  - '>'
  - 4.5
- - lime pentagon
  - '#17E474'
  - p
  - 4.5
- - lime green plus
  - '#8FB327'
  - P
  - 5.4
- - teal star
  - '#449C8C'
  - '*'
  - 6.75
- - pink hexagon
  - '#EA83B7'
  - h
  - 4.5
- - purple rotated hexagon
  - '#902499'
  - H
  - 4.5
- - blue cross
  - '#648FFF'
  - X
  - 4.5
- - dark lavender diamond
  - '#785EF0'
  - D
  - 3.38
- - deep pink thin diamond
  - '#DC267F'
  - d
  - 4.05
- - dark orange circle
  - '#FE6100'
  - o
  - 4.27
- - orange square
  - '#FFB000'
  - s
  - 4.05
- - yellow up-pointing triangle
  - '#FDDF49'
  - ^
  - 4.5
- - lime down-pointing triangle
  - '#17E474'
  - v
  - 4.5
- - lime green left-pointing triangle
  - '#8FB327'
  - <
  - 4.5
- - teal right-pointing triangle
  - '#449C8C'
  - '>'
  - 4.5
- - pink pentagon
  - '#EA83B7'
  - p
  - 4.5
- - purple plus
  - '#902499'
  - P
  - 5.4
- - blue star
  - '#648FFF'
  - '*'
  - 6.75
- - dark lavender hexagon
  - '#785EF0'
  - h
  - 4.5
- - deep pink rotated hexagon
  - '#DC267F'
  - H
  - 4.5
- - dark orange cross
  - '#FE6100'
  - X
  - 4.5
- - orange diamond
  - '#FFB000'
  - D
  - 3.38
- - yellow thin diamond
  - '#FDDF49'
  - d
  - 4.05
- - lime circle
  - '#17E474'
  - o
  - 4.27
- - lime green square
  - '#8FB327'
  - s
  - 4.05
- - teal up-pointing triangle
  - '#449C8C'
  - ^
  - 4.5
- - pink down-pointing triangle
  - '#EA83B7'
  - v
  - 4.5
- - purple left-pointing triangle
  - '#902499'
  - <
  - 4.5
- - blue right-pointing triangle
  - '#648FFF'
  - '>'
  - 4.5
- - dark lavender pentagon
  - '#785EF0'
  - p
  - 4.5
- - deep pink plus
  - '#DC267F'
  - P
  - 5.4
- - dark orange star
  - '#FE6100'
  - '*'
  - 6.75
- - orange hexagon
  - '#FFB000'
  - h
  - 4.5
- - yellow rotated hexagon
  - '#FDDF49'
  - H
  - 4.5
- - lime cross
  - '#17E474'
  - X
  - 4.5
- - lime green diamond
  - '#8FB327'
  - D
  - 3.38
- - teal thin diamond
  - '#449C8C'
  - d
  - 4.05
- - pink circle
  - '#EA83B7'
  - o
  - 4.27
- - purple square
  - '#902499'
  - s
  - 4.05
- - blue up-pointing triangle
  - '#648FFF'
  - ^
  - 4.5
- - dark lavender down-pointing triangle
  - '#785EF0'
  - v
  - 4.5
- - deep pink left-pointing triangle
  - '#DC267F'
  - <
  - 4.5
- - dark orange right-pointing triangle
  - '#FE6100'
  - '>'
  - 4.5
- - orange pentagon
  - '#FFB000'
  - p
  - 4.5
- - yellow plus
  - '#FDDF49'
  - P
  - 5.4
