name: pytest

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  # Normal tests
  test:
    name: Run standard tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Install pulsar_spectra
        run: uv sync --locked --all-extras --dev
      - name: Run pytest
        run: uv run pytest -m "not long"  # Skip long tests


  # Long running Bayesian tests (only after PR approved)
  long-tests:
    name: Run long tests after approval
    if: >
      github.event_name == 'pull_request_review' &&
      github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    needs: test  # Only run if normal tests passed first
    strategy:
      matrix:
        python-version:
          - "3.12"
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install pulsar_spectra
        run: uv sync --locked --all-extras --dev

      - name: Run long tests
        run: uv run pytest -m long