name: Update CSV and Commit
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
on:
  push:
    branches:
      - main
    paths:
      - src/pulsar_spectra/catalogue.py
  pull_request:
    paths:
      - src/pulsar_spectra/catalogue.py
jobs:
  update-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Run Update Script
        run: |
          cd docs
          python get_ref_number_freq_range.py
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: docs/papers_in_catalogue.csv
          commit_message: Update papers_in_catalogue.csv file [skip ci]
